name: Action Workflow

#Actions are code that you write and you can use it in your workflow.

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      #Use github official checkout action to clone your repo
      - name: checkout
        uses: actions/checkout@v1
      - name: List Files
        #GITHUB_SHA git commit hash value
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      #Use JS actions which are located in another github repo
      - name: Simple JS Action
        id: greet
        # @ you can reference specific commit,branch,version(tags)...
        uses: actions/hello-world-javascript-action@v1
        #provide input:
        with:
          who-to-greet: Stevan
      - name: Log Greeting time
        #Acess output variable which github make avaliable to us you have to reference specific ID for that step.
        run: echo "${{ steps.greet.outputs.time }}"
      