#Name of entire workflow
name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        #Pipe caracter can be used to run multiple commands in shell
        run: |         
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        #Inform git actions to run your commands in different shell (not in bash which is by default)
        shell: python
  run-windows-command:
    #Jobs are running in parallel by default you can set up it to run one by on using need keyword which will make your job 
    #dependant of another job and it will be executed only if your first job is successful.
    needs: ["run-shell-command"]
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory using bash
        run: pwd
        shell: bash